# Generated by Django 4.1.1 on 2022-09-13 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_postdata_user_lasttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('content', models.CharField(default='null', max_length=225)),
                ('reviewTime', models.DateTimeField(auto_now_add=True)),
                ('reviewId', models.CharField(default='null', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastTime',
            new_name='loginTime',
        ),
        migrations.AddField(
            model_name='postdata',
            name='postId',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='postdata',
            name='postTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postdata',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
