# Generated by Django 4.1.1 on 2022-09-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_reviewdata_rename_lasttime_user_logintime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='postTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reviewdata',
            name='reviewTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='loginTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
