# Generated by Django 4.1.1 on 2022-09-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_user_logintime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='loginTime',
        ),
        migrations.AddField(
            model_name='user',
            name='lastLogin',
            field=models.CharField(default=-1, max_length=114514),
        ),
    ]
