# Generated by Django 4.1.1 on 2022-09-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_user_logintime_user_lastlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loginid',
            field=models.CharField(default=-1, max_length=20),
        ),
    ]
